### ISSUE TITLE
Replace all occurrences of 'assert' with 'with' in tests

### ISSUE THREAD

**Issue by kiok46** [CashScript/cashscript#226]
From March 26th, 2024 'assert' keyword has been deprecated and replaced by 'with' [link](https://github.com/nodejs/node/releases/tag/v18.20.0)

Old
```js
import artifact from '../fixture/announcement.json' assert { type: 'json' };
```

New
```js
import artifact from '../fixture/announcement.json' with { type: 'json' };
```

> which will be removed in a future semver-major Node.js
> release.

Can confirm the statement above as tests work on node version `v22.10.0` once replacement is done. All tests pass with `TESTS_USE_MOCKNET=true`. (transaction-builder test fails due to no support for mock provider)

**Comment by mr-zwets** [comment]
Thanks for opening the PR! We'll get this merged during our next work session 💪 

Documenting that this would change (break) our compatibility with older node versions:

https://stackoverflow.com/questions/78876691/syntaxerror-unexpected-identifier-assert-on-json-import-in-node-v22
