### ISSUE TITLE
FullStackNetworkProvider failing P2SH32 tests

### ISSUE THREAD

**Issue by mr-zwets** [CashScript/cashscript#231]
Currently the `FullStackNetworkProvider` tests are skipped because they fail...

```ts
describe.skip('P2PKH (using FullStackNetworkProvider)', () => {
  let p2pkhInstance: Contract;
```

We get an error when calling `.send()` 

````
Object {
      "error": Object {
        "error": "Invalid Argument: Must provide a `hash` or `hashBuffer` property",
        "success": false,
      },
      "success": false,
    }

```

it seems the `await bchjs.Electrumx.utxo()` somehow does not support P2SH32 like
`bitcoincash:pdpjeyus929guj00y3sz3ec8ehd2v73e4art9v7prsvke5yujvt5vs6mz82xa`

We tested this with upgrading to the latest is `6.8.0` before we were still at `"@psf/bch-js": "^4.15.0"

**Comment by christroutner** [comment]
FullStack is still running Fulcrum v1.2.3 which is quite old at this point and does not include updates for CashTokens or BitInts. I'm in the process of updating it and will update this issue when it is complete. We'll see if that solves the issue.

**Comment by christroutner** [comment]
I just updated FullStack.cash to the latest version of Fulcrum. @mr-zwets go ahead and try again. Let me know if you still see the issue or not.

**Comment by mr-zwets** [comment]
@christroutner discovered the issue was not with the version of fulcrum but with the `addressToScripthash` function of the fulcrum REST-api

I opened an issue for P2SH32 support on the fulcrum-api repo with a suggested solution 😄 👍 
https://github.com/Permissionless-Software-Foundation/fulcrum-api/issues/13

**Comment by christroutner** [comment]
Continuing this conversation [there](https://github.com/Permissionless-Software-Foundation/fulcrum-api/issues/13).

**Comment by mr-zwets** [comment]
Issue has been resolved upstream! 🙏  

pending PR to enable the p2sh32 test for the `FullStackNetworkProvider`
