### ISSUE TITLE
Transaction evaluation using libauth

### ISSUE THREAD

**Issue by rkalis** [CashScript/cashscript#72]
Libauth has a builtin VM implementation that can be used to locally evaluate a transaction before sending it to the network. We use this in the automated tests for AnyHedge and it would be great to include that functionality in the CashScript SDK.

**Comment by mr-zwets** [comment]
We can close this issue as we now use Libauth for local transaction evaultion for the CashScript debugging tooling.
This was merged today and released in v0.10.0 🥳
