### ISSUE TITLE
BitAuth IDE Integration

### ISSUE THREAD

**Issue by cgcardona** [CashScript/cashscript#8]
[BitJason suggested](https://twitter.com/bitjson/status/1164244656466669568)

> It would be fun to get CashScript integrated into http://ide.bitauth.com. I don't think it would be too difficult either (if you have some form of source map to map output and errors back to source text). At the very least, it could be imported from the "Import Script" dialog.

Sync w/ Rosco regarding

* source map to map output
* errors back to source text

**Comment by mr-zwets** [comment]
related to #76 if we plan to use the "import template" option

**Comment by mr-zwets** [comment]
BitauthIDE integration for debugging has been added as of v0.10.0! 🥳
