### ISSUE TITLE
CashScript debugger using BitJason's TS Script VM

### ISSUE THREAD

**Issue by cgcardona** [CashScript/cashscript#9]
[Rosco suggested](https://twitter.com/RoscoKalis/status/1164245416877199361)

> Would love to collaborate on this. Another idea I had was to use your Typescript Script VM to create a full fledged CashScript debugger. There's a lot of integrations that can be done between our projects I think! Love your work @bitjson

Research more [using `bitcoin-ts` to create CashScript Debugger](https://medium.com/@bitjson/evaluate-and-debug-bitcoin-cash-scripts-in-javascript-3e182136000d)

**Comment by rkalis** [comment]
More info about the Bitcoin TypeScript VM: https://bitauth.github.io/bitcoin-ts/interfaces/authenticationvirtualmachine.html

**Comment by mr-zwets** [comment]
Closing this issue as we do use libauth (previously [bitcoin-ts](https://blog.bitjson.com/bitcoin-ts-is-now-libauth/)) for transaction debugging 🥳
